controller_manager:
ros_parameters:
  ros__parameters:
    update_rate: 200
    use_sim_time: true

    effort_controller:
    	type: effort_controllers/JointGroupEffortController
    	
    mpc_controller:
      type: mpc_controller/MPCController
      
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    imu_sensor_broadcaster:
      imu_sensor_broadcaster/IMUSensorBroadcaster

joint_state_broadcaster:
      ros__parameters:
        joints:
            - FL_HAA
            - FL_HFE
            - FL_KFE
            - FR_HAA
            - FR_HFE
            - FR_KFE
            - HL_HAA
            - HL_HFE
            - HL_KFE
            - HR_HAA
            - HR_HFE
            - HR_KFE
        interfaces:
            - position
            - velocity
            - effort
            
imu_sensor_broadcaster:
	ros__parameters:
		sensor_name: imu_sensor
		frame_id: base

mpc_controller:
  ros__parameters:
    use_sim_time: true

    robot_name: solo12
    sample_time: 0.0025   # 1/400
    
    use_estimator: false        # ! Must be the same as the use_estimator in the planner

    q_init:
      -  0.0
      -  0.3
      - -0.6
      -  0.0
      -  0.3
      - -0.6
      -  0.0
      - -0.3
      -  0.6
      -  0.0
      - -0.3
      -  0.6

    joints:
      - FL_HAA
      - FL_HFE
      - FL_KFE
      - FR_HAA
      - FR_HFE
      - FR_KFE
      - HL_HAA
      - HL_HFE
      - HL_KFE
      - HR_HAA
      - HR_HFE
      - HR_KFE

      tau_max: 2.7
      tau_min: -2.7
      mu: 0.6
      f_max: 15.
      f_min: 2.
