controller_manager:
ros_parameters:
  ros__parameters:
    update_rate: 200
    use_sim_time: true

    mpc_controller:
      type: mpc_controller/MPCController

joint_state_broadcaster:
      ros__parameters:
        joints:
            - FL_HAA
            - FL_HFE
            - FL_KFE
            - FR_HAA
            - FR_HFE
            - FR_KFE
            - HL_HAA
            - HL_HFE
            - HL_KFE
            - HR_HAA
            - HR_HFE
            - HR_KFE
        interfaces:
            - position
            - velocity
            - effort

mpc_controller:
  ros_parameters:
    use_sim_time: true

    robot_name: solo12
    sample_time: 0.0025   # 1/400
    
    use_estimator: false        # ! Must be the same as the use_estimator in the planner

    q_init:
      -  0.0
      -  0.3
      - -0.6
      -  0.0
      -  0.3
      - -0.6
      -  0.0
      - -0.3
      -  0.6
      -  0.0
      - -0.3
      -  0.6

    joints:
      - FL_HAA
      - FL_HFE
      - FL_KFE
      - FR_HAA
      - FR_HFE
      - FR_KFE
      - HL_HAA
      - HL_HFE
      - HL_KFE
      - HR_HAA
      - HR_HFE
      - HR_KFE

      tau_max: 2.7
      tau_min: -2.7
      mu: 0.6
      f_max: 15.
      f_min: 2.
